# Generated by Django 5.0.6 on 2024-07-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pfp',
            field=models.CharField(default='default.png', max_length=50, null=True),
        ),
    ]
