# Generated by Django 5.0.6 on 2024-07-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carrito_det_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='arte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.arte'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Det_carrito',
        ),
    ]
